#Task1


In [2]:
import numpy as np

x = np.arange(2,33, 2).reshape(4,4)

print(x)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


#Task2

In [7]:
import numpy as np

x = np.arange(1,26).reshape(5,5)
y = x[x%2 != 0]
print(y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


#Task3


In [8]:
import numpy as np

x = np.arange(1,5).reshape(4,1)*np.ones((1,4))
print(x)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


#Task4


In [9]:
from google.colab import drive
drive.mount('/NumPy.ipynb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)

# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipynb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-1.54480961  0.79048566  0.8580607  ... -0.36014265 -1.11305182
   0.58071573]
 [ 0.77300692 -0.40871476 -0.69703516 ... -1.29006454 -1.20355175
   1.56239945]
 [-0.98663875  0.97377255 -0.74273192 ...  0.47488925 -1.41633023
   1.11301265]
 ...
 [ 0.3754904   1.45481545  1.05631433 ... -1.01945235  1.05549248
   1.56239945]
 [-1.40681165 -1.31629144 -0.39684261 ... -1.35051298  1.12319472
  -0.30272994]
 [-1.2990222   0.99012528 -1.13291194 ... -0.33905599 -1.17591819
   0.43649392]]
Average of all values in X_norm: 1.0658141036401502e-18
Average of minimum values in each column of X_norm: -1.730053333492847
Average of maximum values in each column of X_norm: 1.7209187813577589
Random permutation of row indices: [156 846  44 325 906 700 743 946 964 614 260 632 799 985 981 205  89 669
 258 234 288 445 138 879 712 631 546  13 315 653 313 219 269 208 478  77
 387 442  12 131 231 710 